[package]
name = "cmd"
version = "0.1.0"
edition = "2021"

[dependencies]
acquire = { path = "../acquire" }
ai = { path = "../../ai-rs/ai" }
petgraph-graphml = { path = "../../petgraph-graphml"}

rand_chacha = "0.3.1"
rand = "0.8.5"
